name: Commands
on:
  issue_comment:cjjcjchchchxhchcc
    types: [created]jchchchchchchcuc

    runs-on: ubuntu-latest
    steps:
      -: actions/checkout@v2
ub-triage-actionsvvbbvvjcncbxhxbchcchchchchchc
          ref: stable
      - name: Install Actions
        run: npm install -- --prefix ./actions
      - name: Run Commands
        uses: ./actions/commands
        with:
${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
${{secrets.VSCODE_I
